### ISSUE TITLE
role root does not exists

### ISSUE THREAD

**Issue by ashwin31** [taigaio/taiga-back#387] opened 2015-07-01 12:20 UTC
I tried to install taiga as per the document http://taigaio.github.io/taiga-doc/dist/setup-production.html

but ran into issues after the command
python manage.py migrate --noinput
Trying import local.py settings...
Trying import development.py settings...
Traceback (most recent call last):
  File "/home/taiga-back/env/lib/python3.4/site-packages/django/db/backends/__init__.py", line 133, in ensure_connection
    self.connect()
  File "/home/taiga-back/env/lib/python3.4/site-packages/transaction_hooks/mixin.py", line 75, in connect
    super(TransactionHooksDatabaseWrapperMixin, self).connect(*a, **kw)
  File "/home/taiga-back/env/lib/python3.4/site-packages/django/db/backends/__init__.py", line 122, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/taiga-back/env/lib/python3.4/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 130, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/taiga-back/env/lib/python3.4/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
psycopg2.OperationalError: FATAL:  role "root" does not exist

**Comment by jespino** [comment] 2015-07-01 12:34
Your problem is related to the user authentication in postgresql. I think the problem is you are installing it as root, but has created the database user "taiga", you can try with this commands to create the "root" user in your database:

```
sudo -u postgres createuser root
sudo -u postgres createdb root -O root
```

Anyway, we prefer to install as a normal user (not root), because root permissions aren't needed.

I will close the issue, because isn't a bug.

**Closed by jespino** 2015-07-01 12:34 UTC

**Comment by bameda** [comment] 2015-07-01 12:37
And please, use our mailing list for setup problems or support questions 

https://groups.google.com/forum/#!forum/taigaio

Thank you very much

Regards
