### ISSUE TITLE
It's not yet possible to have a user story with tasks on different sprint

### ISSUE THREAD

**Issue by allan-simon** [taigaio/taiga-back#561] opened 2016-01-05 12:25 UTC
the use case would be the following

I have a user story made of several tasks (like  User story "cleaning the code"  with tasks "associate all todo with a ticket"  an other "removed commented code" etc.) 

and one of them may be done in Sprint 1 , the other in sprint2 etc.  but it's currently impossible to do so, as a user story and its tasks can only be related to the same sprint.

Of course the current non-optimal workaround is to move the user story to the other sprint, but then the taskboard become polluated with tasks that have been closed in an other sprint

**Comment by superalex** [comment] 2016-01-05 12:41
Hello @allan-simon 

Under a scrum point of view (the one we are following here), a user story should be completed in a sprint and it should be estimated before being included. 

If that user story isn't completed in the sprint it means "problems", it can be an estimation issue, someone in your team is sick, there was an unexpected accident...The spirit of scrum and agile in this point is the visualization of the problem, what most of the teams do in this point is just move the full user story to the following sprint so the problem is pointed and can be fixed.

We had an existing enhancement request to make easy moving tasks from one us to another (https://tree.taiga.io/project/taiga/issue/2656), I'm leaving the Taiga one open and closing this one.

Regards!,

**Comment by allan-simon** [comment] 2016-01-07 10:42
ok, no problem, I confirmed with our "scrum master" and he agrees with your point of view, so no problem, the issue you're linking should make the trick

**Closed** 2016-01-07 10:43 UTC

**Comment by superalex** [comment] 2016-01-07 10:59
Great! :+1:
